// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgGwYoH5HO37eEEI2wUJgYwRi15lCuvsc',
    appId: '1:753456964320:web:7769953bb316a61d136685',
    messagingSenderId: '753456964320',
    projectId: 'assignment2-forum-app',
    authDomain: 'assignment2-forum-app.firebaseapp.com',
    storageBucket: 'assignment2-forum-app.firebasestorage.app',
    measurementId: 'G-EEYHFS63YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrbpKKzwtts_4lxlvHWkCCL6b7_Wap1Yo',
    appId: '1:753456964320:android:ae11b1a7eeb4aa2d136685',
    messagingSenderId: '753456964320',
    projectId: 'assignment2-forum-app',
    storageBucket: 'assignment2-forum-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_OTCvjTHrhIJ6zWjiLX3LryXD_dcsV3o',
    appId: '1:753456964320:ios:83260bc3c1f8e33e136685',
    messagingSenderId: '753456964320',
    projectId: 'assignment2-forum-app',
    storageBucket: 'assignment2-forum-app.firebasestorage.app',
    iosBundleId: 'com.example.forumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_OTCvjTHrhIJ6zWjiLX3LryXD_dcsV3o',
    appId: '1:753456964320:ios:83260bc3c1f8e33e136685',
    messagingSenderId: '753456964320',
    projectId: 'assignment2-forum-app',
    storageBucket: 'assignment2-forum-app.firebasestorage.app',
    iosBundleId: 'com.example.forumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgGwYoH5HO37eEEI2wUJgYwRi15lCuvsc',
    appId: '1:753456964320:web:90a1d0c45a1f983a136685',
    messagingSenderId: '753456964320',
    projectId: 'assignment2-forum-app',
    authDomain: 'assignment2-forum-app.firebaseapp.com',
    storageBucket: 'assignment2-forum-app.firebasestorage.app',
    measurementId: 'G-FM9JCT7KQX',
  );
}
